exception: avoid using __builint_isnan as well
It does seem to misbehave depending on compilation flags so it seems
better to manually check for bit patterns rather than playing further
cat and mouse games with the compiler.