Fix missing stdlib.h include
This fixes an error I was getting when trying to build pyrite64:

libdragon/include/debug.h:284:17: error: ‘abort’ was not declared in this scope