exception: improve exception names shown in crash screen
Currently, the crash screen reports the raw MIPS exception name, which
is sometimes not very clear to the programmer. For instance, a NULL
pointer dereference causes a "TLB Load/Instruction miss" which doesn't
really point to the actual reason.

This patch improves __get_exception_name so that it generates an
error string which is clearer to the end user in many cases.