exception: improve error screen for floating point exceptions
Instead of generically report the floating point exception bit name,
we now special case the most common errors to provide accurate diagnostic:

 * Use of invalid floating point value (denormal)
 * Use of uninitialized floating point value (possible thanks to the new
   -fauto-var-init)
 * Negative square root
 * Overflow while casting to integer

Denormals are disproportionally the most common case of floating point
errors, and these are normally caused by accessing invalid memory. We
also add a second line to the exception screen to explain this.