exception: remove workaround for console not working under interrupt
Now that the console is working under interrupt, we can avoid the
workaround used in the default exception handler to exit the exception,
which in turn caused some issues in some cases.